window.NIAONIAO_DATA = {
  "meta": {
    "title": "燕云袅袅查漏",
    "releaseVersion": "1.3.0",
    "dataVersion": "formal-1.3.0",
    "updatedAt": "2026-09-13",
    "sourceRevision": 574,
    "sourceRows": 108,
    "newCount": 3,
    "suppressedNewIds": [
      "src-016",
      "src-020",
      "src-067",
      "src-067-02",
      "src-072-04",
      "src-072-01",
      "src-072-02",
      "src-072-03",
      "src-072-05",
      "src-072-06",
      "src-072-07",
      "src-072-08",
      "src-098",
      "src-099",
      "src-100",
      "src-101",
      "src-102",
      "src-103",
      "src-104",
      "src-105",
      "src-106",
      "src-107",
      "src-108"
    ]
  },
  "items": [
    {
      "id": "src-001",
      "sourceSerial": 1,
      "module": "region",
      "region": "清河",
      "type": "剧情",
      "regionTypeRank": 1,
      "quantity": 1,
      "condition": "残章·夜行刀",
      "displayTitle": "残章·夜行刀",
      "note": "剑影藏心",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-002",
      "sourceSerial": 2,
      "module": "region",
      "region": "清河",
      "type": "剧情",
      "regionTypeRank": 1,
      "quantity": 1,
      "condition": "残章·千金散尽",
      "displayTitle": "残章·千金散尽",
      "note": "蝉翼未来 一代船套  温无痕",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-003",
      "sourceSerial": 3,
      "module": "region",
      "region": "清河",
      "type": "剧情",
      "regionTypeRank": 2,
      "quantity": 1,
      "condition": "奇遇·佛花与鼠（上）",
      "displayTitle": "奇遇·佛花与鼠（上）",
      "note": "慈心镇 五鼠兄弟",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-004",
      "sourceSerial": 4,
      "module": "region",
      "region": "清河",
      "type": "妙妙喵",
      "regionTypeRank": 7,
      "quantity": 2,
      "condition": "清河妙妙喵商店",
      "displayTitle": "清河妙妙喵商店",
      "note": "50铃铛/个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-005",
      "sourceSerial": 5,
      "module": "region",
      "region": "清河",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 8,
      "condition": "清河以武会友（元皓、照微夜、姚凌凌、邱秋仁、房万向、阎鸿、楼百尺、罗伯礼）",
      "displayTitle": "清河以武会友",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-005-01",
          "label": "元皓",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-005-02",
          "label": "照微夜",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-005-03",
          "label": "姚凌凌",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-005-04",
          "label": "邱秋仁",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-005-05",
          "label": "房万向",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-005-06",
          "label": "阎鸿",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-005-07",
          "label": "楼百尺",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-005-08",
          "label": "罗伯礼",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-006",
      "sourceSerial": 6,
      "module": "region",
      "region": "清河",
      "type": "探索度",
      "regionTypeRank": 10,
      "quantity": 2,
      "condition": "清河区域探索度6级",
      "displayTitle": "清河区域探索度6级",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-007",
      "sourceSerial": 7,
      "module": "region",
      "region": "开封",
      "type": "剧情",
      "regionTypeRank": 2,
      "quantity": 1,
      "condition": "奇遇·疯狂的石头",
      "displayTitle": "奇遇·疯狂的石头",
      "note": "九流门驻地 八音窍仓库",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-008",
      "sourceSerial": 8,
      "module": "region",
      "region": "开封",
      "type": "剧情",
      "regionTypeRank": 4,
      "quantity": 1,
      "condition": "镇守·天上来",
      "displayTitle": "镇守·天上来",
      "note": "河伯",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-009",
      "sourceSerial": 9,
      "module": "region",
      "region": "开封",
      "type": "剧情",
      "regionTypeRank": 5,
      "quantity": 1,
      "condition": "侠迹·公子书",
      "displayTitle": "侠迹·公子书",
      "note": "南烛公子 寒姨身世",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-010",
      "sourceSerial": 10,
      "module": "region",
      "region": "开封",
      "type": "玩法",
      "regionTypeRank": 6,
      "quantity": 1,
      "condition": "赵飞烟私库",
      "displayTitle": "赵飞烟私库",
      "note": "8w宋元/个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-011",
      "sourceSerial": 11,
      "module": "region",
      "region": "开封",
      "type": "妙妙喵",
      "regionTypeRank": 7,
      "quantity": 3,
      "condition": "开封妙妙喵商店",
      "displayTitle": "开封妙妙喵商店",
      "note": "40妙妙钱币/个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-012",
      "sourceSerial": 12,
      "module": "region",
      "region": "开封",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 6,
      "condition": "开封以武会友（裴衔、丁远、不平生、胡衍、花间客、淮南客）",
      "displayTitle": "开封以武会友",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-012-01",
          "label": "裴衔",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-012-02",
          "label": "丁远",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-012-03",
          "label": "不平生",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-012-04",
          "label": "胡衍",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-012-05",
          "label": "花间客",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-012-06",
          "label": "淮南客",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-013",
      "sourceSerial": 13,
      "module": "region",
      "region": "开封",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 4,
      "condition": "九流门驻地四海豪客（夺命、热血、有情、妙手）",
      "displayTitle": "九流门驻地四海豪客",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-013-01",
          "label": "夺命",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-013-02",
          "label": "热血",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-013-03",
          "label": "有情",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-013-04",
          "label": "妙手",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-014",
      "sourceSerial": 14,
      "module": "region",
      "region": "开封",
      "type": "地方小册",
      "regionTypeRank": 9,
      "quantity": 2,
      "condition": "花间集-八级、九级",
      "displayTitle": "花间集",
      "note": "地图-樊楼区域显示",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-014-01",
          "label": "花间集八级",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-014-02",
          "label": "花间集九级",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-015",
      "sourceSerial": 15,
      "module": "region",
      "region": "开封",
      "type": "地方小册",
      "regionTypeRank": 9,
      "quantity": 2,
      "condition": "鬼间集-十四级、十九级",
      "displayTitle": "鬼间集",
      "note": "地图-鬼市子区域显示",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-015-01",
          "label": "鬼间集十四级",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-015-02",
          "label": "鬼间集十九级",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-016",
      "sourceSerial": 16,
      "module": "region",
      "region": "开封",
      "type": "地方小册",
      "regionTypeRank": 9,
      "quantity": 1,
      "condition": "风闻笺-风媒顾问",
      "displayTitle": "风闻笺-风媒顾问",
      "note": "文章累计被点赞2400次",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-017",
      "sourceSerial": 17,
      "module": "region",
      "region": "开封",
      "type": "区域探索度",
      "regionTypeRank": 9007199254740991,
      "quantity": 2,
      "condition": "开封区域探索度6级",
      "displayTitle": "开封区域探索度6级",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-018",
      "sourceSerial": 18,
      "module": "region",
      "region": "开封皇宫",
      "type": "剧情",
      "regionTypeRank": 1,
      "quantity": 1,
      "condition": "残章·高堂野客上",
      "displayTitle": "残章·高堂野客上",
      "note": "赵光义委托 四大神偷",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-019",
      "sourceSerial": 19,
      "module": "region",
      "region": "开封皇宫",
      "type": "剧情",
      "regionTypeRank": 1,
      "quantity": 1,
      "condition": "残章·高堂野客下",
      "displayTitle": "残章·高堂野客下",
      "note": "韩微行刺 过招阿原",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-020",
      "sourceSerial": 20,
      "module": "region",
      "region": "开封皇宫",
      "type": "剧情",
      "regionTypeRank": 3,
      "quantity": 1,
      "condition": "探游·酒香不怕埋得深",
      "displayTitle": "探游·酒香不怕埋得深",
      "note": "变成小狗",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-021",
      "sourceSerial": 21,
      "module": "region",
      "region": "开封皇宫",
      "type": "地方小册",
      "regionTypeRank": 9,
      "quantity": 2,
      "condition": "宫廷秘史-三级、六级",
      "displayTitle": "宫廷秘史",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-021-01",
          "label": "宫廷秘史三级",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-021-02",
          "label": "宫廷秘史六级",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-022",
      "sourceSerial": 22,
      "module": "region",
      "region": "开封皇宫",
      "type": "地方小册",
      "regionTypeRank": 9,
      "quantity": 2,
      "condition": "斗师手册-掌盆名家、盖世虫王",
      "displayTitle": "斗师手册",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-022-01",
          "label": "斗师手册·掌盆名家",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-022-02",
          "label": "斗师手册·盖世虫王",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-023",
      "sourceSerial": 23,
      "module": "region",
      "region": "开封皇宫",
      "type": "玩法",
      "regionTypeRank": 6,
      "quantity": 2,
      "condition": "皇宫秘库-打开12个柜子",
      "displayTitle": "皇宫秘库-打开12个柜子",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-024",
      "sourceSerial": 24,
      "module": "region",
      "region": "开封皇宫",
      "type": "玩法",
      "regionTypeRank": 6,
      "quantity": 1,
      "condition": "七个小雪人",
      "displayTitle": "七个小雪人",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-025",
      "sourceSerial": 25,
      "module": "region",
      "region": "开封皇宫",
      "type": "探索度",
      "regionTypeRank": 10,
      "quantity": 2,
      "condition": "开封皇宫区域探索度5级",
      "displayTitle": "开封皇宫区域探索度5级",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-026",
      "sourceSerial": 26,
      "module": "region",
      "region": "开封皇宫",
      "type": "妙妙喵",
      "regionTypeRank": 7,
      "quantity": 2,
      "condition": "开封皇宫妙妙喵商店",
      "displayTitle": "开封皇宫妙妙喵商店",
      "note": "20御鱼干/个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-027",
      "sourceSerial": 27,
      "module": "region",
      "region": "开封皇宫",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 4,
      "condition": "开封皇宫四海豪客（陈红娘、高怀德、申九、张恨棠&李卫宋）",
      "displayTitle": "开封皇宫四海豪客",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-027-01",
          "label": "陈红娘",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-027-02",
          "label": "高怀德",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-027-03",
          "label": "申九",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-027-04",
          "label": "张恨棠&李卫宋",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-028",
      "sourceSerial": 28,
      "module": "region",
      "region": "河西",
      "type": "剧情",
      "regionTypeRank": 4,
      "quantity": 1,
      "condition": "镇守·大散关",
      "displayTitle": "镇守·大散关",
      "note": "镇关吼",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-029",
      "sourceSerial": 29,
      "module": "region",
      "region": "河西",
      "type": "剧情",
      "regionTypeRank": 4,
      "quantity": 1,
      "condition": "镇守·陷城湖",
      "displayTitle": "镇守·陷城湖",
      "note": "月中狮",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-030",
      "sourceSerial": 30,
      "module": "region",
      "region": "河西",
      "type": "剧情",
      "regionTypeRank": 4,
      "quantity": 1,
      "condition": "镇守·鱼在藻也",
      "displayTitle": "镇守·鱼在藻也",
      "note": "赤鲤公",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-031",
      "sourceSerial": 31,
      "module": "region",
      "region": "河西",
      "type": "剧情",
      "regionTypeRank": 5,
      "quantity": 1,
      "condition": "侠迹·太平归处",
      "displayTitle": "侠迹·太平归处",
      "note": "秦川 大石狮子",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-032",
      "sourceSerial": 32,
      "module": "region",
      "region": "河西",
      "type": "剧情",
      "regionTypeRank": 5,
      "quantity": 1,
      "condition": "侠迹·凯风徐来",
      "displayTitle": "侠迹·凯风徐来",
      "note": "青灯夜 帷帽女",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-033",
      "sourceSerial": 33,
      "module": "region",
      "region": "河西",
      "type": "地方小册",
      "regionTypeRank": 9,
      "quantity": 1,
      "condition": "池锦集-四级",
      "displayTitle": "池锦集-四级",
      "note": "和玉门关天涯客对话获得",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-034",
      "sourceSerial": 34,
      "module": "region",
      "region": "河西",
      "type": "探索度",
      "regionTypeRank": 10,
      "quantity": 2,
      "condition": "河西区域探索度6级",
      "displayTitle": "河西区域探索度6级",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-035",
      "sourceSerial": 35,
      "module": "region",
      "region": "河西",
      "type": "妙妙喵",
      "regionTypeRank": 7,
      "quantity": 3,
      "condition": "河西妙妙喵商店",
      "displayTitle": "河西妙妙喵商店",
      "note": "30漠漠宝/个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-036",
      "sourceSerial": 36,
      "module": "region",
      "region": "河西",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 2,
      "condition": "玉门关以武会友(苟保仁、贾龙王）",
      "displayTitle": "玉门关以武会友",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-036-01",
          "label": "苟保仁",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-036-02",
          "label": "贾龙王",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-037",
      "sourceSerial": 37,
      "module": "region",
      "region": "河西",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 5,
      "condition": "凉州以武会友(文修、颠倒生、林中、李醉风、程放)",
      "displayTitle": "凉州以武会友",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-037-01",
          "label": "文修",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-037-02",
          "label": "颠倒生",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-037-03",
          "label": "林中",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-037-04",
          "label": "李醉风",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-037-05",
          "label": "程放",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-038",
      "sourceSerial": 38,
      "module": "region",
      "region": "河西",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 7,
      "condition": "秦川四海豪客(孟济川、赵途、平五丈、袁天罡、卫陵鸦、周季、高继思)",
      "displayTitle": "秦川四海豪客",
      "note": "先击败卫陵鸦才能见到高继思",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-038-01",
          "label": "孟济川",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-038-02",
          "label": "赵途",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-038-03",
          "label": "平五丈",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-038-04",
          "label": "袁天罡",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-038-05",
          "label": "卫陵鸦",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-038-06",
          "label": "周季",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-038-07",
          "label": "高继思",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-039",
      "sourceSerial": 39,
      "module": "region",
      "region": "河西",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 1,
      "condition": "风摧凉州以武愈心（施家德）",
      "displayTitle": "风摧凉州以武愈心（施家德）",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-040",
      "sourceSerial": 40,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 2,
      "quantity": 1,
      "condition": "奇遇·不义之约",
      "displayTitle": "奇遇·不义之约",
      "note": "双结局慎重选择",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-041",
      "sourceSerial": 41,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 3,
      "quantity": 1,
      "condition": "探游·影灯戏话（完成第一章）",
      "displayTitle": "探游·影灯戏话（完成第一章）",
      "note": "获得任意一个皮影后解锁",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-042",
      "sourceSerial": 42,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 3,
      "quantity": 1,
      "condition": "探游·滹沱之名",
      "displayTitle": "探游·滹沱之名",
      "note": "刻碑100个侠名可得",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-043",
      "sourceSerial": 43,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 4,
      "quantity": 1,
      "condition": "镇守·墨守之心",
      "displayTitle": "镇守·墨守之心",
      "note": "张万师",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-044",
      "sourceSerial": 44,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 4,
      "quantity": 1,
      "condition": "镇守·飞天残垣",
      "displayTitle": "镇守·飞天残垣",
      "note": "青",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-045",
      "sourceSerial": 45,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 5,
      "quantity": 1,
      "condition": "侠迹·山中见墨",
      "displayTitle": "侠迹·山中见墨",
      "note": "坠机后和冯大哥进山",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-046",
      "sourceSerial": 46,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 5,
      "quantity": 1,
      "condition": "侠迹·薤露存辉",
      "displayTitle": "侠迹·薤露存辉",
      "note": "墨门三位先辈（启昭、陈途、匡安世）",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-047",
      "sourceSerial": 47,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 5,
      "quantity": 1,
      "condition": "侠迹·揽星为衿",
      "displayTitle": "侠迹·揽星为衿",
      "note": "天文学家王贞仪",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-048",
      "sourceSerial": 48,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 5,
      "quantity": 1,
      "condition": "侠迹·奉敕不杀",
      "displayTitle": "侠迹·奉敕不杀",
      "note": "滹沱栾城 赵铁寻子",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-049",
      "sourceSerial": 49,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 5,
      "quantity": 1,
      "condition": "侠迹·芦中曲",
      "displayTitle": "侠迹·芦中曲",
      "note": "芦花 采薇",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-050",
      "sourceSerial": 50,
      "module": "region",
      "region": "不见山",
      "type": "玩法",
      "regionTypeRank": 6,
      "quantity": 1,
      "condition": "鲮货郎-尖货店",
      "displayTitle": "鲮货郎-尖货店",
      "note": "145残侯翅/个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-051",
      "sourceSerial": 51,
      "module": "region",
      "region": "不见山",
      "type": "玩法",
      "regionTypeRank": 6,
      "quantity": 1,
      "condition": "鲮货郎-后勤铺淘宝点",
      "displayTitle": "鲮货郎-后勤铺淘宝点",
      "note": "5墨赏/个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-052",
      "sourceSerial": 52,
      "module": "region",
      "region": "不见山",
      "type": "玩法",
      "regionTypeRank": 6,
      "quantity": 1,
      "condition": "琳琅商店",
      "displayTitle": "琳琅商店",
      "note": "10猴赛雷/个（捕猎马猴）",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-053",
      "sourceSerial": 53,
      "module": "region",
      "region": "不见山",
      "type": "妙妙喵",
      "regionTypeRank": 7,
      "quantity": 3,
      "condition": "不见山妙妙喵商店",
      "displayTitle": "不见山妙妙喵商店",
      "note": "40金算珠/个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-054",
      "sourceSerial": 54,
      "module": "region",
      "region": "不见山",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 4,
      "condition": "不见山以武会友（雁九笙、甄士贾、裘武、风侠客）",
      "displayTitle": "不见山以武会友",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-054-02",
          "label": "雁九笙",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-054-03",
          "label": "甄士贾",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-054-04",
          "label": "裘武",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-054-05",
          "label": "风侠客",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-055",
      "sourceSerial": 55,
      "module": "region",
      "region": "不见山",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 6,
      "condition": "不见山四海豪客（酒千岁、卞从远、耶律广、李振、肖然、风四海）",
      "displayTitle": "不见山四海豪客",
      "note": "林芊芊没有袅袅",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-054-01",
          "label": "酒千岁",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-055-01",
          "label": "卞从远",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-055-02",
          "label": "耶律广",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-055-03",
          "label": "李振",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-055-04",
          "label": "肖然",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-055-05",
          "label": "风四海",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-056",
      "sourceSerial": 56,
      "module": "region",
      "region": "不见山",
      "type": "地方小册",
      "regionTypeRank": 9,
      "quantity": 1,
      "condition": "一扇门-学徒工一阶",
      "displayTitle": "一扇门-学徒工一阶",
      "note": "完成探游·一扇门・修治机关后解锁",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-057",
      "sourceSerial": 57,
      "module": "region",
      "region": "不见山",
      "type": "探索度",
      "regionTypeRank": 10,
      "quantity": 2,
      "condition": "不见山区域探索度6级",
      "displayTitle": "不见山区域探索度6级",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-058",
      "sourceSerial": 58,
      "module": "region",
      "region": "青州",
      "type": "剧情",
      "regionTypeRank": 4,
      "quantity": 1,
      "condition": "镇守·风雪岱山",
      "displayTitle": "镇守·风雪岱山",
      "note": "裴航",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-059",
      "sourceSerial": 59,
      "module": "region",
      "region": "青州",
      "type": "妙妙喵",
      "regionTypeRank": 7,
      "quantity": 2,
      "condition": "青州妙妙喵商店",
      "displayTitle": "青州妙妙喵商店",
      "note": "30金核桃/个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-060",
      "sourceSerial": 60,
      "module": "region",
      "region": "青州",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 7,
      "condition": "青州四海豪客（楚一振、沈韩杨、柳晏如、林行逸、谢长庚、季浮真、卢以诚）",
      "displayTitle": "青州四海豪客",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-060-01",
          "label": "楚一振",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-060-02",
          "label": "沈韩杨",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-060-03",
          "label": "柳晏如",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-060-04",
          "label": "林行逸",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-060-05",
          "label": "谢长庚",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-060-06",
          "label": "季浮真",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-060-07",
          "label": "卢以诚",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-061",
      "sourceSerial": 61,
      "module": "region",
      "region": "青州",
      "type": "地方小册",
      "regionTypeRank": 9,
      "quantity": 2,
      "condition": "文津学牒-开蒙四、游学贯通四",
      "displayTitle": "文津学牒",
      "note": "游学贯通四需要成为文津馆正式弟子",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-061-01",
          "label": "文津学牒·开蒙四",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-061-02",
          "label": "文津学牒·游学贯通四",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-062",
      "sourceSerial": 62,
      "module": "region",
      "region": "青州",
      "type": "探索度",
      "regionTypeRank": 10,
      "quantity": 2,
      "condition": "青州区域探索度5级",
      "displayTitle": "青州区域探索度5级",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-063",
      "sourceSerial": 63,
      "module": "region",
      "region": "江南",
      "type": "剧情",
      "regionTypeRank": 0,
      "quantity": 1,
      "condition": "主章·最忆江南",
      "displayTitle": "主章·最忆江南",
      "note": "陈叔接你下江南",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-064",
      "sourceSerial": 64,
      "module": "region",
      "region": "江南",
      "type": "剧情",
      "regionTypeRank": 5,
      "quantity": 1,
      "condition": "侠迹·聊赠一枝春",
      "displayTitle": "侠迹·聊赠一枝春",
      "note": "大侠多读书",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-065",
      "sourceSerial": 65,
      "module": "region",
      "region": "江南",
      "type": "剧情",
      "regionTypeRank": 4,
      "quantity": 1,
      "condition": "镇守·无明春山",
      "displayTitle": "镇守·无明春山",
      "note": "传奇调查员少年陈子奚",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-066",
      "sourceSerial": 66,
      "module": "region",
      "region": "江南",
      "type": "剧情",
      "regionTypeRank": 4,
      "quantity": 1,
      "condition": "镇守·大雾幽篁",
      "displayTitle": "镇守·大雾幽篁",
      "note": "竹林大战愁铃客",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-067-group",
      "sourceSerial": 67,
      "module": "region",
      "region": "江南",
      "type": "地方小册",
      "regionTypeRank": 9,
      "quantity": 2,
      "condition": "尝草录-杭城隐逸·八、杭城居士·十二",
      "displayTitle": "尝草录·杭城隐逸",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-067",
          "label": "杭城隐逸·八",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-067-02",
          "label": "杭城居士·十二",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-068",
      "sourceSerial": 68,
      "module": "region",
      "region": "江南",
      "type": "玩法",
      "regionTypeRank": 6,
      "quantity": 1,
      "condition": "零花钱",
      "displayTitle": "零花钱",
      "note": "迟早斋撬锁",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-069",
      "sourceSerial": 69,
      "module": "region",
      "region": "江南",
      "type": "玩法",
      "regionTypeRank": 6,
      "quantity": 1,
      "condition": "入港稽查",
      "displayTitle": "入港稽查",
      "note": "第四天奖励",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-070",
      "sourceSerial": 70,
      "module": "region",
      "region": "江南",
      "type": "探索度",
      "regionTypeRank": 10,
      "quantity": 3,
      "condition": "江南区域探索度4级、6级",
      "displayTitle": "江南区域探索度",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-070-01",
          "label": "区域探索度4级",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-070-02",
          "label": "区域探索度6级",
          "quantity": 2,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-071",
      "sourceSerial": 71,
      "module": "region",
      "region": "江南",
      "type": "妙妙喵",
      "regionTypeRank": 7,
      "quantity": 3,
      "condition": "江南妙妙喵商店",
      "displayTitle": "江南妙妙喵商店",
      "note": "40金莲瓣/个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-072",
      "sourceSerial": 72,
      "module": "region",
      "region": "江南",
      "type": "故人",
      "regionTypeRank": 8,
      "quantity": 8,
      "condition": "江南四海豪客（凌非羽、夜行客、陈慎、洛逢春、周远信、冷三、叶来归、吴断刀）",
      "displayTitle": "江南四海豪客",
      "note": "叶来归在探游中，吴断刀在镇守中，无法在地图看到",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-072-04",
          "label": "凌非羽",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-072-01",
          "label": "夜行客",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-072-02",
          "label": "陈慎",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-072-03",
          "label": "洛逢春",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-072-05",
          "label": "周远信",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-072-06",
          "label": "冷三",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-072-07",
          "label": "叶来归",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-072-08",
          "label": "吴断刀",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-073",
      "sourceSerial": 73,
      "module": "gameplay",
      "region": "其它",
      "type": "固定获取",
      "regionTypeRank": 9007199254740991,
      "quantity": 2,
      "condition": "试炼（黑财神、公子书）",
      "displayTitle": "试炼",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-073-01",
          "label": "试炼·黑财神",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-073-02",
          "label": "试炼·公子书",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-074",
      "sourceSerial": 74,
      "module": "gameplay",
      "region": "其它",
      "type": "固定获取",
      "regionTypeRank": 9007199254740991,
      "quantity": 2,
      "condition": "外观图鉴·单品收集进度（80、160）",
      "displayTitle": "外观图鉴·单品收集进度",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-074-01",
          "label": "外观图鉴·单品收集进度80",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-074-02",
          "label": "外观图鉴·单品收集进度160",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-075",
      "sourceSerial": 75,
      "module": "gameplay",
      "region": "其它",
      "type": "固定获取",
      "regionTypeRank": 9007199254740991,
      "quantity": 10,
      "condition": "武库造诣（2.6w、3w、3.4w、3.8w、4.2w、4.6w、5w、5.4w、5.8w、6.2w）",
      "displayTitle": "武库造诣",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [
        {
          "id": "src-075-01",
          "label": "武库造诣2.6万",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-075-02",
          "label": "武库造诣3万",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-075-03",
          "label": "武库造诣3.4万",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-075-04",
          "label": "武库造诣3.8万",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-075-05",
          "label": "武库造诣4.2万",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-075-06",
          "label": "武库造诣4.6万",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-075-07",
          "label": "武库造诣5万",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-075-08",
          "label": "武库造诣5.4万",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-075-09",
          "label": "武库造诣5.8万",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-075-10",
          "label": "武库造诣6.2万",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-076",
      "sourceSerial": 76,
      "module": "gameplay",
      "region": "其它",
      "type": "固定获取",
      "regionTypeRank": 9007199254740991,
      "quantity": 1,
      "condition": "闯荡·捕风寻影",
      "displayTitle": "闯荡·捕风寻影",
      "note": "回忆进度20",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-077",
      "sourceSerial": 77,
      "module": "gameplay",
      "region": "其它",
      "type": "固定获取",
      "regionTypeRank": 9007199254740991,
      "quantity": 1,
      "condition": "家业·家业繁荣度-1级",
      "displayTitle": "家业·家业繁荣度-1级",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-078",
      "sourceSerial": 78,
      "module": "gameplay",
      "region": "其它",
      "type": "固定获取",
      "regionTypeRank": 9007199254740991,
      "quantity": 1,
      "condition": "清河庄客云游-六级",
      "displayTitle": "清河庄客云游-六级",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-079",
      "sourceSerial": 79,
      "module": "gameplay",
      "region": "其它",
      "type": "固定获取",
      "regionTypeRank": 9007199254740991,
      "quantity": 1,
      "condition": "不见山庄客云游-第六境",
      "displayTitle": "不见山庄客云游-第六境",
      "note": "",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-080",
      "sourceSerial": 80,
      "module": "limited",
      "region": "其它",
      "type": "固定刷新",
      "regionTypeRank": 9007199254740991,
      "quantity": 2,
      "condition": "止戈·赛季境界（刀光戈影一重境、挥戈反日—重境）",
      "displayTitle": "止戈·赛季境界",
      "note": "2026·6·26-2026·9·24  赛季刷新",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "season",
      "children": [
        {
          "id": "src-080-01",
          "label": "刀光戈影一重境",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-080-02",
          "label": "挥戈反日一重境",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-081",
      "sourceSerial": 81,
      "module": "limited",
      "region": "其它",
      "type": "固定刷新",
      "regionTypeRank": 9007199254740991,
      "quantity": 3,
      "condition": "止戈·觉障林无我（单排、双排、五排）",
      "displayTitle": "止戈·觉障林无我",
      "note": "2026·8·27-2026·9·4 赛季刷新",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "season",
      "children": [
        {
          "id": "src-081-01",
          "label": "觉障林·单排达到无我",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-081-02",
          "label": "觉障林·双排达到无我",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-081-03",
          "label": "觉障林·五排达到无我",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-082",
      "sourceSerial": 82,
      "module": "limited",
      "region": "其它",
      "type": "固定刷新",
      "regionTypeRank": 9007199254740991,
      "quantity": 2,
      "condition": "江湖百珍",
      "displayTitle": "江湖百珍",
      "note": "200长鸣玉/个 每周刷新",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "weekly",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-083",
      "sourceSerial": 83,
      "module": "limited",
      "region": "其它",
      "type": "固定刷新",
      "regionTypeRank": 9007199254740991,
      "quantity": 1,
      "condition": "不肝商店",
      "displayTitle": "不肝商店",
      "note": "200长鸣玉/个 每周刷新",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "weekly",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-084",
      "sourceSerial": 84,
      "module": "limited",
      "region": "其它",
      "type": "固定刷新",
      "regionTypeRank": 9007199254740991,
      "quantity": 2,
      "condition": "地华商店",
      "displayTitle": "地华商店",
      "note": "12地华/个  每月刷新",
      "countdownEnd": null,
      "refreshRule": "monthly",
      "refreshAt": null,
      "expiresAt": null,
      "period": "monthly",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-085",
      "sourceSerial": 85,
      "module": "limited",
      "region": "其它",
      "type": "固定刷新",
      "regionTypeRank": 9007199254740991,
      "quantity": 2,
      "condition": "逐战商店",
      "displayTitle": "逐战商店",
      "note": "3000花蕊织/个   2026·6·26-2026·9·24 赛季刷新",
      "countdownEnd": null,
      "refreshRule": "scheduled",
      "refreshAt": "2026-09-24T04:59:59+08:00",
      "expiresAt": null,
      "period": "season",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-086",
      "sourceSerial": 86,
      "module": "limited",
      "region": "其它",
      "type": "限时活动",
      "regionTypeRank": 9007199254740991,
      "quantity": 3,
      "condition": "邮件·1亿谢礼",
      "displayTitle": "邮件·1亿谢礼",
      "note": "2026·8·28开始连续3天陆续发完",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "event",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-087",
      "sourceSerial": 87,
      "module": "limited",
      "region": "其它",
      "type": "限时活动",
      "regionTypeRank": 9007199254740991,
      "quantity": 10,
      "condition": "邮件·科隆游戏展最佳移动游戏",
      "displayTitle": "邮件·科隆游戏展最佳移动游戏",
      "note": "2026·8·28开始连续7天陆续发完",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "event",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-088-group",
      "sourceSerial": 88,
      "module": "limited",
      "region": "其它",
      "type": "限时活动",
      "regionTypeRank": 9007199254740991,
      "quantity": 2,
      "condition": "玉振扬音-有馀依",
      "displayTitle": "玉振扬音-有馀依",
      "note": "每180抽内必得一个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": "2026-09-24T04:59:59+08:00",
      "period": "event",
      "children": [
        {
          "id": "src-088",
          "label": "玉振扬音·第1枚",
          "quantity": 1,
          "isNew": false
        },
        {
          "id": "src-088-02",
          "label": "玉振扬音·第2枚",
          "quantity": 1,
          "isNew": false
        }
      ],
      "isNew": false
    },
    {
      "id": "src-089",
      "sourceSerial": 89,
      "module": "chance",
      "region": "其它",
      "type": "概率获取",
      "regionTypeRank": 9007199254740991,
      "quantity": 5,
      "condition": "逐战商店",
      "displayTitle": "逐战商店",
      "note": "200花蕊织/1个逐战惊喜礼盒  每周可买5个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "weekly",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-090",
      "sourceSerial": 90,
      "module": "chance",
      "region": "其它",
      "type": "概率获取",
      "regionTypeRank": 9007199254740991,
      "quantity": 3,
      "condition": "百业商店",
      "displayTitle": "百业商店",
      "note": "200宝珠/1个百业惊喜礼盒 每周可买3个",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "weekly",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-091",
      "sourceSerial": 91,
      "module": "chance",
      "region": "其它",
      "type": "概率获取",
      "regionTypeRank": 9007199254740991,
      "quantity": 2,
      "condition": "闯荡·群力共伐",
      "displayTitle": "闯荡·群力共伐",
      "note": "每周可领取2次奖励",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "weekly",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-092",
      "sourceSerial": 92,
      "module": "chance",
      "region": "其它",
      "type": "概率获取",
      "regionTypeRank": 9007199254740991,
      "quantity": null,
      "condition": "战令宝箱",
      "displayTitle": "战令宝箱",
      "note": "赛季战令",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "season",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-093",
      "sourceSerial": 93,
      "module": "chance",
      "region": "其它",
      "type": "概率获取",
      "regionTypeRank": 9007199254740991,
      "quantity": null,
      "condition": "闲趣·烟花晚会",
      "displayTitle": "闲趣·烟花晚会",
      "note": "每周六、日晚20：30   开附近频道的利是封",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "weekly",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-094",
      "sourceSerial": 94,
      "module": "chance",
      "region": "其它",
      "type": "概率获取",
      "regionTypeRank": 9007199254740991,
      "quantity": null,
      "condition": "浮景行舟·盛宴礼盒",
      "displayTitle": "浮景行舟·盛宴礼盒",
      "note": "盛宴时刻宝箱",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-095",
      "sourceSerial": 95,
      "module": "limited",
      "region": "其它",
      "type": "限时活动",
      "regionTypeRank": 9007199254740991,
      "quantity": 1,
      "condition": "游山问水-敬香问吉-求财运",
      "displayTitle": "游山问水-敬香问吉-求财运",
      "note": "",
      "countdownEnd": "2026-09-17T04:59:59+08:00",
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "event",
      "children": [],
      "isNew": true
    },
    {
      "id": "src-096",
      "sourceSerial": 96,
      "module": "gameplay",
      "region": "其它",
      "type": "固定获取",
      "regionTypeRank": 9007199254740991,
      "quantity": 1,
      "condition": "渡尘沙-藏品-宝华积分奖励",
      "displayTitle": "渡尘沙-藏品-宝华积分奖励",
      "note": "达到16000积分",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": true
    },
    {
      "id": "src-097",
      "sourceSerial": 97,
      "module": "limited",
      "region": "其它",
      "type": "限时活动",
      "regionTypeRank": 9007199254740991,
      "quantity": 1,
      "condition": "侠心筑绿茵",
      "displayTitle": "侠心筑绿茵",
      "note": "9月1日后直接领取",
      "countdownEnd": "2026-09-10T04:59:59+08:00",
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "event",
      "children": [],
      "isNew": true
    },
    {
      "id": "src-098",
      "sourceSerial": 98,
      "module": "region",
      "region": "河西",
      "type": "剧情",
      "regionTypeRank": 0,
      "quantity": 1,
      "condition": "主章·麻布袋",
      "displayTitle": "主章·麻布袋",
      "note": "刘三杨 棉花种子",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-099",
      "sourceSerial": 99,
      "module": "region",
      "region": "河西",
      "type": "剧情",
      "regionTypeRank": 0,
      "quantity": 1,
      "condition": "主章·凉州曲",
      "displayTitle": "主章·凉州曲",
      "note": "廉道子 小琵琶",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-100",
      "sourceSerial": 100,
      "module": "region",
      "region": "河西",
      "type": "剧情",
      "regionTypeRank": 0,
      "quantity": 1,
      "condition": "主章·纸月亮",
      "displayTitle": "主章·纸月亮",
      "note": "安琉璃 曹敬观音",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-101",
      "sourceSerial": 101,
      "module": "region",
      "region": "河西",
      "type": "剧情",
      "regionTypeRank": 0,
      "quantity": 1,
      "condition": "主章·秦川梦别",
      "displayTitle": "主章·秦川梦别",
      "note": "画睛兄 寻找三只画笔",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-102",
      "sourceSerial": 102,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 0,
      "quantity": 1,
      "condition": "主章·离人故事",
      "displayTitle": "主章·离人故事",
      "note": "与盈盈晋中原会合 接阎王镖",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-103",
      "sourceSerial": 103,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 0,
      "quantity": 1,
      "condition": "主章·桃源迷津",
      "displayTitle": "主章·桃源迷津",
      "note": "冯大哥 继升机进山",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-104",
      "sourceSerial": 104,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 0,
      "quantity": 1,
      "condition": "主章·百鸟齐喑",
      "displayTitle": "主章·百鸟齐喑",
      "note": "墨门往事",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-105",
      "sourceSerial": 105,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 0,
      "quantity": 1,
      "condition": "主章·矢落金乌",
      "displayTitle": "主章·矢落金乌",
      "note": "隼曾对燕说：木鸟会带来新朋友",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-106",
      "sourceSerial": 106,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 0,
      "quantity": 1,
      "condition": "主章·天灾人祸",
      "displayTitle": "主章·天灾人祸",
      "note": "冯大哥黄袍加身",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-107",
      "sourceSerial": 107,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 0,
      "quantity": 1,
      "condition": "主章·坠日煮海",
      "displayTitle": "主章·坠日煮海",
      "note": "飞天城坠毁开山 江南前奏",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    },
    {
      "id": "src-108",
      "sourceSerial": 108,
      "module": "region",
      "region": "不见山",
      "type": "剧情",
      "regionTypeRank": 4,
      "quantity": 1,
      "condition": "镇守·滹沱旧事",
      "displayTitle": "镇守·滹沱旧事",
      "note": "萧翰",
      "countdownEnd": null,
      "refreshRule": null,
      "refreshAt": null,
      "expiresAt": null,
      "period": "once",
      "children": [],
      "isNew": false
    }
  ]
};
